import { createContext } from "react";

import type { DynamicBoardCard } from "@/core/context/dynamic-board-context";
import type {
  MockCardContent,
  MockCardContentCustomData,
} from "@/example/types";

export type AddEditCardModalState =
  | {
      data: null; // Clear the data on close.
      mode: "close";
    }
  | {
      data: Omit<DynamicBoardCard, "id"> & {
        // Omit card id because it will be generated by the board.
        rowId: string | null; // We need to pass the rowId in which the card will be added to that row. If null, the card will be added to the last row.
        customCardData?: MockCardContentCustomData; // This is optional because in add mode, the customCardData is not yet available.
      };
      mode: "add";
    }
  | {
      // For edit mode, we need to pass whole card data.
      data: DynamicBoardCard<MockCardContent>;
      mode: "edit";
    };

export interface ExampleBoardContextType {
  showOpenEditModal: AddEditCardModalState;
  /**
   * Opens the add/edit card modal.
   * @param modalData.mode - The mode for the modal.
   * @param modalData.data - The data for the modal.
   * @param modalData.data.rowId - The rowId for the modal. Only need when adding a new card to a specific row.
   * @param modalData.data.layoutJson - The layoutJson for the modal.
   * @param modalData.data.customCardData - The customCardData for the modal. Only need when editing a card.
   */
  setShowOpenEditModal: (modalData: AddEditCardModalState) => void;
}

export const ExampleBoardContext =
  createContext<ExampleBoardContextType | null>(null);

export function createExampleBoardContext() {
  return createContext<ExampleBoardContextType | null>(null);
}
