#!/bin/sh

# Format all staged files
prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown

# Add the formatted files back to the index
git update-index --again